# Generated by Django 2.2.6 on 2019-10-23 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The Title of the Project', max_length=50)),
                ('abstract', models.FileField(upload_to='')),
                ('literature', models.FileField(upload_to='')),
                ('method', models.FileField(upload_to='')),
                ('analysis', models.FileField(upload_to='')),
                ('conclusion', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField(help_text='The abstract of the Student Project')),
                ('literature', models.TextField(help_text='The literature of the Student Project')),
                ('method', models.TextField(help_text='The method of the Student Project')),
                ('analysis', models.TextField(help_text='The analysis of the Student Project')),
                ('conclusion', models.TextField(help_text='The conclusion of the Student Project')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='st_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
