# Generated by Django 2.2.6 on 2019-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_myuser_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('E', 'Examiner'), ('A', 'Admin')], default='Admin', max_length=30),
            preserve_default=False,
        ),
    ]
