# Generated by Django 2.2.6 on 2019-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20191023_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.FloatField()),
                ('literature', models.FloatField()),
                ('method', models.FloatField()),
                ('analysis', models.FloatField()),
                ('conclusion', models.FloatField()),
            ],
        ),
    ]
