# Generated by Django 2.2.6 on 2019-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='abstract',
            field=models.FloatField(help_text='States the grading value for the section'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='analysis',
            field=models.FloatField(help_text='States the grading value for the section'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='conclusion',
            field=models.FloatField(help_text='States the grading value for the section'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='literature',
            field=models.FloatField(help_text='States the grading value for the section'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='method',
            field=models.FloatField(help_text='States the grading value for the section'),
        ),
    ]
